name: devoca-deploy

services:
  redis:
    image: redis:7.2
    container_name: devoca_redis
    restart: unless-stopped
    networks:
      - devoca_network
    env_file:
      - ".env"
    deploy:
      resources:
        limits:
          memory: 512M
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 512M

  api:
    build:
      context: "../DEVoca-api/"
      dockerfile: Dockerfile
    container_name: devoca_api
    restart: unless-stopped
    networks:
      - devoca_network
    env_file:
      - ".env"

  jenkins:
    image: jenkins/jenkins:2.442-jdk17
    container_name: devoca_jenkins
    restart: unless-stopped
    ports:
      - "${JENKINS_PORT}:8080"
    volumes:
      - "./jenkins/jenkins_home:/var/jenkins_home:rw"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/usr/bin/docker-compose:/usr/bin/docker-compose"

  mysql:
    image: mysql:8.0.35
    container_name: devoca_mysql
    restart: unless-stopped
    networks:
      - devoca_network
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_PORT}"
    volumes:
      - "../DEVoca-api/resources/sql/:/docker-entrypoint-initdb.d/"
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    command: --character-set-server=utf8mb4  --collation-server=utf8mb4_bin

  frontend:
    build:
      context: "../DEVoca-frontend/"
      dockerfile: Dockerfile
    env_file:
      - ".env"
    volumes:
      - "/etc/nginx/html:/build"

  nginx:
    image: nginx:1.25
    container_name: devoca_nginx
    restart: unless-stopped
    networks:
      - devoca_network
    env_file:
      - ".env"
    ports:
      - "${NGINX_PORT}:443"
    volumes:
      - "./.cert/:/.cert/:ro"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro"
      - "/etc/nginx/html:/usr/share/nginx/html"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:
  jenkins_home:

networks:
  devoca_network:
    name: devoca_network
    external: true
